.PHONY: $(CRUDE_CLEAN)-$(LOCAL_MODULE) $(CRUDE_CLEAN)-$(LOCAL_TARGET_ID) $(addprefix $(CRUDE_CLEAN)-, $(LOCAL_LABELS))
ifneq ($(LOCAL_MODULE),$(LOCAL_TARGET_ID))
    $(CRUDE_CLEAN)-$(LOCAL_MODULE): $(CRUDE_CLEAN)-$(LOCAL_TARGET_ID)
endif
$(addprefix $(CRUDE_CLEAN)-, $(LOCAL_LABELS)): $(CRUDE_CLEAN)-$(LOCAL_TARGET_ID)
$(CRUDE_CLEAN): $(CRUDE_CLEAN)-$(LOCAL_TARGET_ID)

$(CRUDE_CLEAN)-$(LOCAL_TARGET_ID): PRIVATE_TARGET_ID := $(LOCAL_TARGET_ID)
$(CRUDE_CLEAN)-$(LOCAL_TARGET_ID): PRIVATE_RMS := $(LOCAL_INTERMEDIATE) $(LOCAL_SUBTARGETS) $(LOCAL_TARGET)
$(CRUDE_CLEAN)-$(LOCAL_TARGET_ID):
	@echo "Removing output of $(PRIVATE_TARGET_ID)"
	$(CRUDE_AT)rm -fr $(PRIVATE_RMS)
