ifndef CRUDE_RULE_STATICLIB
CRUDE_RULE_STATICLIB := 1
endif

ifeq ($(LOCAL_TARGET),)
    LOCAL_TARGET := $(CRUDE_OUT)/lib/lib$(LOCAL_MODULE).a
endif

EXPORT_LDFLAGS += $(LOCAL_TARGET)

LOCAL_CFLAGS += -fPIC
LOCAL_CXXFLAGS += -fPIC
include $(CRUDE_DIR)/crude-common-compile.mk

$(LOCAL_TARGET): PRIVATE_OBJS := $(LOCAL_OBJS)
$(LOCAL_TARGET): PRIVATE_ARFLAGS := $(LOCAL_ARFLAGS)
$(LOCAL_TARGET): PRIVATE_IMPORTS := $(LOCAL_IMPORTS)
$(LOCAL_TARGET):
	@mkdir -p $(dir $@) && echo '[1;33mSTATICLIB [0;33m$@[0m'
	@rm -f $@
	$(CRUDE_AT)$(AR) $(if $(PRIVATE_ARFLAGS),$(PRIVATE_ARFLAGS),$(ARFLAGS)) $@ $(PRIVATE_OBJS)
